version: '3'
services:
  client:
    build: ./client
    ports:
      - "80:80"
  api:
    build: ./api
    ports:
      - "3001:3001"
    depends_on:
      - python-service
  python-service:
    build: ./python-service
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=atrox123
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: atrox123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
